### ISSUE TITLE
update README.md with description and principles

### ISSUE THREAD

**Issue by t-izbassar** [t-izbassar/rainy-day#2]

**Comment by 0pdd** [comment]
@t-izbassar 3 puzzles [#17](https://github.com/t-izbassar/rainy-day/issues/17), [#18](https://github.com/t-izbassar/rainy-day/issues/18), [#19](https://github.com/t-izbassar/rainy-day/issues/19) are still not solved.

**Comment by 0pdd** [comment]
@t-izbassar 2 puzzles [#17](https://github.com/t-izbassar/rainy-day/issues/17), [#18](https://github.com/t-izbassar/rainy-day/issues/18) are still not solved; solved: [#19](https://github.com/t-izbassar/rainy-day/issues/19).

**Comment by 0pdd** [comment]
@t-izbassar the puzzle [#18](https://github.com/t-izbassar/rainy-day/issues/18) is still not solved; solved: [#17](https://github.com/t-izbassar/rainy-day/issues/17), [#19](https://github.com/t-izbassar/rainy-day/issues/19).

**Comment by 0pdd** [comment]
@t-izbassar all 3 puzzles are solved here: [#17](https://github.com/t-izbassar/rainy-day/issues/17), [#18](https://github.com/t-izbassar/rainy-day/issues/18), [#19](https://github.com/t-izbassar/rainy-day/issues/19).
